### PR TITLE
update to yarn 0.27.3

### PR DESCRIPTION
**Pull request by Banford**
I've updated the binary to 0.27.3 as I've found that the earlier version used by the current VSTS task does not work with our private npm registry located on VSTS. Using 0.27.3 locally can locate our private packages so I'm thinking upgrading to this version will fix the issue on the VSTS build agent.

Related to https://github.com/yarnpkg/yarn/issues/2541.

Please could you tag and create a 0.8.0 release once this is merged?

### CODE REVIEW

**Comment by Banford** [comment]
This has been superseded by the latest commit, which updates to 0.27.5 Thanks!

**Comment by sandorfr** [comment]
Yes, but the bad news, is that the task is now hanging on our test builds. So I have to investigate the cause before I can publish it.

**Comment by Banford** [comment]
@sandorfr ok no worries. Maybe roll back a minor version and see if the issue persists?

**Comment by sandorfr** [comment]
Hi @Banford, I've finally published the update as I noticed our test build was hanging because of some version conflict in the package.json / lack of lockfile.

**Pull request closed without merging**
